### PR TITLE
PHP 8.1 cosmetics

### PR DESCRIPTION
**Pull request by mambax7**
- refactor tagBar() function into a class (mamba)
- various cosmetics (mamba)
- trigger_error() (mamba)
- fixed update_stats(): replaced ADD with AND in $criteria->add(new \Criteria('tag_modid', $modid), 'ADD'); (mamba)
- reversed missing tag_modid in getByLimit() (mamba)
- updated sample.php (mamba)
- reversed some changes in blocks.php (mamba)
- lowered limit_cloud_list from 100 to 10 (mamba)
- added xmnews plugin (mage)
- updated instructions for creating a plugin (mage)
- fix: when using the tags for the first time, the id was displayed in the field (maga)
- added Blocksadmin (mamba)
- PHP 8.1 cosmetics and type hinting (mamba)

### CODE REVIEW

**Comment by mambax7** [comment]
Yes, it's better to wait for the next official Beta release, since there will be still few more changes coming

**Comment by mambax7** [comment]
Hi @alain01, I'm going to take break with this module, so go ahead with the templates and testing. If you don't find any serious bugs, I'll release it as Beta 4

**Comment by alain01** [comment]
Hi @mambax7 
So I test and work with this PR #29 or you merge it now ?

**Comment by mambax7** [comment]
Just download it from my account: https://github.com/mambax7/tag/

**Comment by alain01** [comment]
Ok, that's clear for me, TY.

**Comment by alain01** [comment]
Ok, I'm working on bt4 tpl.

**Pull request merged**
